# This file has been generated automatically with HTR-United <3 Github Actions form
name: htrvx
'on':
  - push
  - pull_request
jobs:
  HTRVX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install htrvx
      - name: Run HTRVX
        run: |
          htrvx --verbose --group --format alto --check-empty --segmonto --xsd --raise-empty ./data/*.xml

